### ISSUE TITLE
Proposal: Hosting multiple API documentation for different DART versions

### ISSUE THREAD

**Issue by jslee02** [dartsim/dart#710]
#### Tasks
- [X] create a repo for API documentation hosting: [dartsim/api](https://github.com/dartsim/api)
- [x] upload API documentations
- [x] update [DART website](http://dartsim.github.io/)

**Comment by jslee02** [comment]
This could be done using multiple GitHub repositories. [GitHub Pages](https://pages.github.com/) allows us to host webpage per repository. The html files could be in master branch or gh-pages branch. For example, I created [jslee02/v6.0.1](https://github.com/jslee02/v6.1.0) and put the API html files generated by doxygen at the master branch, and [this](https://jslee02.github.io/v6.1.0/) is the website of it. We could have multiple dartsim/[VERSION] repositories in similar way.

One thing I'm not sure is which version of API documentation should be maintained. We could host:
(1) master, most recent versions of each major release like: 6.1.1, 5.1.4, and 4.3.6
(2) master, most recent versions of each minor release like: 6.0.1, 6.1.1, 5.0.x, and so on

I think (1) would be a reasonable option since we intend to keep the API compatibility within the same major version.

**Comment by psigen** [comment]
I don't know if multiple repos is the right way to handle this. We would end up with hundreds of them over time, which seems wildly unmanageable.

What is the downside of building docs into subdirectories of a single `gh-pages` branch? The normal branches of the repo could be individual doc versions, with the special `gh-pages` branch having a built version of each per subdirectory? This update could be done as a post automated build step.

**Comment by jslee02** [comment]
Hm, I haven't tested if subdirectories work. If so, it sounds better solution. I'll test now.

**Comment by jslee02** [comment]
It works perfectly! Thanks @psigen .

Okay then we could host as many versions as we want.

I think we could use master branch for having the subdirectory instead of gh-pages since the repo is only for API hosting but not for other source or something like [this](https://github.com/jslee02/v6.1.0/tree/master).

**Comment by psigen** [comment]
Sure ` gh-pages` is just the default, but master makes sense if it's a pure
documentation repository.

**Comment by jslee02** [comment]
I believe this issue is resolved. (see: http://dartsim.github.io/dart/).
